# Generated by Django 3.1.12 on 2021-06-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredientes',
            new_name='ingredients',
        ),
    ]
